docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Usage: usage.md
site_name: zend-xml2json
site_description: "Convert XML documents to JSON"
repo_url: 'https://github.com/zendframework/zend-xml2json'
